# Generated by Django 3.1 on 2020-09-29 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_month', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('student_class', models.CharField(max_length=5)),
                ('amount', models.IntegerField(help_text='Payment Amount in Tk.')),
                ('date', models.DateField(help_text='Date of payment.')),
                ('payment_for_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuinfo.studentpaymentinfo')),
            ],
        ),
    ]
