# Generated by Django 3.1 on 2020-09-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='student_institution',
            field=models.CharField(blank=True, help_text='Enter school name.', max_length=100, null=True),
        ),
    ]
