# Generated by Django 3.1.1 on 2020-09-23 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_lang', models.CharField(help_text='Enter book language.', max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.booklanguage'),
        ),
    ]
