# Generated by Django 3.1.1 on 2020-09-23 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200923_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.booklanguage'),
        ),
    ]
