# Generated by Django 3.1.1 on 2020-09-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200923_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_langinBook',
            new_name='book_langinorigin',
        ),
    ]
