# Generated by Django 3.1.1 on 2020-09-23 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200923_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_langinorigin',
            new_name='book_langinBook',
        ),
    ]
