# Generated by Django 3.1.1 on 2020-09-25 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200923_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_date',
            new_name='date_of_death',
        ),
    ]
